// src/js/constants/action-types.tsx
// ACTIONS
/* @flow */
export default class Actions {
  static FETCH_DATA =  "FETCH_DATA";
  static FETCH_DATA_LOADING =  "FETCH_DATA_LOADING";
  static FETCH_DATA_RECEIVED =   "FETCH_DATA_RECEIVED";
  static FETCH_DATA_ERROR =  "FETCH_DATA_ERROR";
  static GET_APP_RECOMMENDATION_SUCCESS = "GET_APP_RECOMMENDATION_SUCCESS";
  static TOP_FREE_APP_100_SUCCESS = "TOP_FREE_APP_100_SUCCESS"
  static APP_RATING_SUCCESS = "APP_RATING_SUCCESS"
  static FETCH_MORE = "FETCH_MORE"
  static SHOW_ERROR = "SHOW_ERROR"

}